<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.osm</groupId>
    <artifactId>osm-project</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>osm-project</name>
    <description>Aggregator build for all OSM Maven modules</description>

    <modules>
        <module>osm-parent</module>
        <module>osm-eureka</module>
        <module>osm-sec</module>
        <module>osm-fin</module>
        <module>osm-pack</module>
        <module>osm-prod</module>
        <module>osm-cond</module>
        <module>osm-hr</module>
        <module>osm-gateway</module>
    </modules>
</project>
